In [2]:
import tensorflow as tf

gpu_options = tf.GPUOptions(visible_device_list="3")
config = tf.ConfigProto(allow_soft_placement=True, log_device_placement=True, device_count={'GPU': 1}, gpu_options=gpu_options)
config.gpu_options.per_process_gpu_memory_fraction = 0.25
sess = tf.Session(config=config)


In [3]:
import numpy as np

In [4]:
W = np.array([1,2,3])
x = np.array([4,5,6])
MatMul = np.matmul(W,x)
print(MatMul)
b = np.array([7])
Add = np.add(MatMul, b)
print(Add)

32
[39]


In [5]:
import tensorflow as tf

a = tf.constant(3.0)
b = tf.constant(2.0)

output = a+b
print(output)
print(a)


with tf.Session(config=config) as sess :
    result = sess.run(output)
    print(result)

Tensor("add:0", shape=(), dtype=float32)
Tensor("Const:0", shape=(), dtype=float32)
5.0


In [6]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

output = a+b

with tf.Session(config=config) as sess:
    result = sess.run(output, feed_dict= {
        a:[3.0, 4.0],
        b:[2.0, 3.0]
    })
    print(result)

[5. 7.]


In [11]:
a = tf.placeholder(tf.float32)
b = tf.Variable(1.0)

output = a+tf.assign(b, b*2)

with tf.Session(config=config) as sess:
    sess.run(tf.global_variables_initializer())
    
    print(sess.run(output, feed_dict={a:3.0}))
    print(sess.run(output, feed_dict={a:3.0}))
    print(sess.run(output, feed_dict={a:3.0})) 
    print(sess.run(output, feed_dict={a:3.0}))        

5.0
7.0
11.0
19.0


In [8]:
tf.reset_default_graph()

In [7]:
DATA_X1 = [0,0,1,1]
DATA_X2 = [0,1,0,1]

W1 = tf.constant(1.0)
W2 = tf.constant(1.0)
B = tf.constant(-1.5)

X1 = tf.placeholder(tf.float32)
X2 = tf.placeholder(tf.float32)

output = X1*W1 + X2*W2 + B

with tf.Session(config=config) as sess:
    result = sess.run(output, feed_dict={X1:DATA_X1, X2:DATA_X2})
    print(result)

[-1.5 -0.5 -0.5  0.5]


In [8]:
tf.reset_default_graph()

In [9]:
DATA_X = [[0,0],[0,1],[1,0],[1,1]]

W = tf.constant([[1.0], [1.0]])
B = tf.constant(-1.5)

X = tf.placeholder(tf.float32)

output = tf.matmul(X,W) + B



In [15]:
with tf.Session(config=config) as sess:
    result = sess.run(output, feed_dict={X:DATA_X})
    print(result)

[[-1.5]
 [-0.5]
 [-0.5]
 [ 0.5]]


In [10]:
tf.reset_default_graph()
def hard_limit(x):
    cond = tf.less(x, tf.zeros(tf.shape(x)))
    return tf.where(cond, tf.zeros(tf.shape(x)), tf.ones(tf.shape(x)))

DATA_X = [[0,0], [0,1], [1,0], [1,1]]

X = tf.placeholder(tf.float32)

W1 = tf.Variable([[1.0,1.0], [1.0,1.0]])
B1 = tf.Variable([-1.5, -0.5])

W2 = tf.Variable([[-1.0], [1.0]])
B2 = tf.Variable(-0.5)

output = hard_limit(tf.matmul(hard_limit(tf.matmul(X,W1) + B1), W2)+B2)

with tf.Session(config=config) as sess:
    sess.run(tf.global_variables_initializer())
    
    result = sess.run(output, feed_dict={X:DATA_X})
    print(result)

[[0.]
 [1.]
 [1.]
 [0.]]


In [13]:
tf.reset_default_graph()

DATA_X = [[0,0], [0,1], [1,0], [1,1]]
DATA_Y = [[0],[1],[1],[0]]

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_normal([2,2]))
b1 = tf.Variable(tf.random_normal([2]))
layer1 = tf.sigmoid(tf.matmul(X,W1) + b1 )

W2 = tf.Variable(tf.random_normal([2,1]))
b2 = tf.Variable(tf.random_normal([1]))
output = tf.sigmoid(tf.matmul(layer1, W2) + b2)

cost = -tf.reduce_mean(Y*tf.log(output) + (1-Y) * tf.log(1-output))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session(config=config) as sess:
    sess.run(tf.global_variables_initializer())
    
    for epoch in range(10000):
        sess.run(train,feed_dict = {X: DATA_X, Y:DATA_Y})
        if epoch % 1000 == 0:
            print(epoch, *sess.run(output, feed_dict={X:DATA_X, Y:DATA_Y}))

0 [0.7543636] [0.76661515] [0.7277197] [0.7374069]
1000 [0.49592787] [0.54351014] [0.47174218] [0.49402502]
2000 [0.4164354] [0.70603126] [0.43051285] [0.42837512]
3000 [0.18927756] [0.87152493] [0.7236414] [0.15514301]
4000 [0.07695757] [0.93893933] [0.89234] [0.06285034]
5000 [0.04493646] [0.9623081] [0.93830496] [0.03705442]
6000 [0.03115019] [0.9731784] [0.9575728] [0.02586218]
7000 [0.02365844] [0.9793195] [0.96789694] [0.01973835]
8000 [0.01899848] [0.98322874] [0.9742667] [0.01590921]
9000 [0.01583661] [0.9859226] [0.9785674] [0.01330034]
